
// ==================================================================
// StampSettingState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Shared
{
  public class StampSettingState : 
    global::Sungero.CoreEntities.Shared.DatabookEntryState, global::Akelon.StampModule.IStampSettingState
  {
    public StampSettingState(global::Akelon.StampModule.IStampSetting entity) : base(entity) { }

    public new global::Akelon.StampModule.IStampSettingPropertyStates Properties
    {
      get { return (global::Akelon.StampModule.IStampSettingPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Akelon.StampModule.Shared.StampSettingPropertyStates(entity);
    }


    public new global::Akelon.StampModule.IStampSettingControlStates Controls
    {
      get { return (global::Akelon.StampModule.IStampSettingControlStates)base.Controls; }
    }

    protected override global::Sungero.Domain.Shared.IEntityControlStates CreateControlStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Akelon.StampModule.Shared.StampSettingControlStates(entity);
    }

    public new global::Akelon.StampModule.IStampSettingPageStates Pages
    {
      get { return (global::Akelon.StampModule.IStampSettingPageStates)base.Pages; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPageStates CreatePageStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::Akelon.StampModule.Shared.StampSettingPageStates(entity);
    }

  }


  public class StampSettingControlStates : 
    global::Sungero.CoreEntities.Shared.DatabookEntryControlStates, global::Akelon.StampModule.IStampSettingControlStates
  {

    protected internal StampSettingControlStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }
  public class StampSettingPageStates : 
    global::Sungero.CoreEntities.Shared.DatabookEntryPageStates, global::Akelon.StampModule.IStampSettingPageStates
  {
        public global::Sungero.Domain.Shared.IStandalonePageState MainPage
        {
        get { return this.GetPageState<Sungero.Domain.Shared.IStandalonePageState>("Card"); }
        }


    protected internal StampSettingPageStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class StampSettingPropertyStates : 
    global::Sungero.CoreEntities.Shared.DatabookEntryPropertyStates, global::Akelon.StampModule.IStampSettingPropertyStates
  {
            public global::Sungero.Domain.Shared.IPropertyState<global::System.String> Name 
            {
              get { return this.GetPropertyState<global::System.String>("Name"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Docflow.IDocumentType> DocumentType 
            {
              get { return this.InternalDocumentType; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Docflow.IDocumentType> InternalDocumentType
            {
              get { return this.GetPropertyState<global::Sungero.Docflow.IDocumentType>("DocumentType"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Core.Enumeration?> StampKind 
            {
              get { return this.GetPropertyState<global::Sungero.Core.Enumeration?>("StampKind"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Core.Enumeration?> DocumentPosition 
            {
              get { return this.GetPropertyState<global::Sungero.Core.Enumeration?>("DocumentPosition"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Core.Enumeration?> PagePosition 
            {
              get { return this.GetPropertyState<global::Sungero.Core.Enumeration?>("PagePosition"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::System.Int32?> SizeHeight 
            {
              get { return this.GetPropertyState<global::System.Int32?>("SizeHeight"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::System.Int32?> SizeWidth 
            {
              get { return this.GetPropertyState<global::System.Int32?>("SizeWidth"); }
            }
            public global::Sungero.Domain.Shared.IDataPropertyState StampImage 
            {
              get { return this.GetDataPropertyState("StampImage"); }
            }


    protected internal StampSettingPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

}

// ==================================================================
// StampSettingInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Shared
{
  public class StampSettingInfo : 
    global::Sungero.CoreEntities.Shared.DatabookEntryInfo, global::Akelon.StampModule.IStampSettingInfo
  {
    public StampSettingInfo(global::System.Type entityType) : base(entityType) { }

    public new global::Akelon.StampModule.IStampSettingPropertiesInfo Properties
    {
      get { return (global::Akelon.StampModule.IStampSettingPropertiesInfo)base.Properties; }
    }

    public new global::Akelon.StampModule.IStampSettingActionsInfo Actions
    {
      get { return (global::Akelon.StampModule.IStampSettingActionsInfo)base.Actions; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::Akelon.StampModule.Shared.StampSettingPropertiesInfo(entityType);
    }

    protected override global::Sungero.Domain.Shared.IEntityActionsInfo CreateEntityActionsInfo(global::System.Type entityType)
    {
      return new global::Akelon.StampModule.Shared.StampSettingActionsInfo(entityType);
    }
  }

  public class StampSettingPropertiesInfo : 
    global::Sungero.CoreEntities.Shared.DatabookEntryPropertiesInfo, global::Akelon.StampModule.IStampSettingPropertiesInfo
  {
        public global::Sungero.Domain.Shared.IStringPropertyInfo Name 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.StringPropertyMetadata>("Name");
             return new global::Sungero.Domain.Shared.StringPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.Docflow.IDocumentTypeInfo, global::Sungero.Docflow.IDocumentType> DocumentType 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("DocumentType");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.Docflow.IDocumentTypeInfo, global::Sungero.Docflow.IDocumentType>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IEnumPropertyInfo StampKind 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.EnumPropertyMetadata>("StampKind");
             return new global::Sungero.Domain.Shared.EnumPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IEnumPropertyInfo DocumentPosition 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.EnumPropertyMetadata>("DocumentPosition");
             return new global::Sungero.Domain.Shared.EnumPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IEnumPropertyInfo PagePosition 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.EnumPropertyMetadata>("PagePosition");
             return new global::Sungero.Domain.Shared.EnumPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IIntegerPropertyInfo SizeHeight 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.IntegerPropertyMetadata>("SizeHeight");
             return new global::Sungero.Domain.Shared.IntegerPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IIntegerPropertyInfo SizeWidth 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.IntegerPropertyMetadata>("SizeWidth");
             return new global::Sungero.Domain.Shared.IntegerPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IImagePropertyInfo StampImage 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.ImagePropertyMetadata>("StampImage");
             return new global::Sungero.Domain.Shared.ImagePropertyInfo(propertyMetadata);
          }
        }


    protected internal StampSettingPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

  public class StampSettingActionsInfo : 
    global::Sungero.Domain.Shared.EntityActionsInfo, global::Akelon.StampModule.IStampSettingActionsInfo
  {
        public global::Sungero.Domain.Shared.IActionInfo LoadStampPicture 
        {
          get { return new global::Sungero.Domain.Shared.ActionInfo(this.GetActionMetadata("LoadStampPicture")); }
        }
        public global::Sungero.Domain.Shared.IActionInfo DeleteStampPicture 
        {
          get { return new global::Sungero.Domain.Shared.ActionInfo(this.GetActionMetadata("DeleteStampPicture")); }
        }


    protected internal StampSettingActionsInfo(global::System.Type entityType) : base(entityType) { }
  }
}

// ==================================================================
// StampSettingHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule
{
  public partial class StampSettingSharedHandlers : global::Sungero.CoreEntities.DatabookEntrySharedHandlers, IStampSettingSharedHandlers
  {
    private global::Akelon.StampModule.IStampSetting _obj
    {
      get { return (global::Akelon.StampModule.IStampSetting)this.Entity; }
    }
    public virtual void NameChanged(global::Sungero.Domain.Shared.StringPropertyChangedEventArgs e) { }


    public virtual void DocumentTypeChanged(global::Akelon.StampModule.Shared.StampSettingDocumentTypeChangedEventArgs e) { }



    public virtual void DocumentPositionChanged(global::Sungero.Domain.Shared.EnumerationPropertyChangedEventArgs e) { }


    public virtual void PagePositionChanged(global::Sungero.Domain.Shared.EnumerationPropertyChangedEventArgs e) { }




    public virtual void StampImageChanged(global::Sungero.Domain.Shared.ImagePropertyChangedEventArgs e) { }




    public StampSettingSharedHandlers(global::Akelon.StampModule.IStampSetting entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// StampSettingResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Shared.StampSetting
{
  /// <summary>
  /// Represents StampSetting resources.
  /// </summary>
  public class StampSettingResources : global::Sungero.CoreEntities.Shared.DatabookEntry.DatabookEntryResources, global::Akelon.StampModule.StampSetting.IStampSettingResources
  {
    public virtual global::CommonLibrary.LocalizedString ErrorNegativeValueSize
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Akelon.StampModule.IStampSetting) , "ErrorNegativeValueSize");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ErrorNegativeValueSizeFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Akelon.StampModule.IStampSetting), "ErrorNegativeValueSize", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString MsgNotImageStamp
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Akelon.StampModule.IStampSetting) , "MsgNotImageStamp");
      }
    }

    public virtual global::CommonLibrary.LocalizedString MsgNotImageStampFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Akelon.StampModule.IStampSetting), "MsgNotImageStamp", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ErrorMsgFindDuplicate
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Akelon.StampModule.IStampSetting) , "ErrorMsgFindDuplicate");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ErrorMsgFindDuplicateFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Akelon.StampModule.IStampSetting), "ErrorMsgFindDuplicate", false, args);
    }

  }
}

// ==================================================================
// StampSettingSharedFunctions.g.cs
// ==================================================================

namespace Akelon.StampModule.Shared
{
  public partial class StampSettingFunctions : global::Sungero.CoreEntities.Shared.DatabookEntryFunctions
  {
    private global::Akelon.StampModule.IStampSetting _obj
    {
      get { return (global::Akelon.StampModule.IStampSetting)this.Entity; }
    }

    public StampSettingFunctions(global::Akelon.StampModule.IStampSetting entity) : base(entity) { }
  }
}

// ==================================================================
// StampSettingFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Functions
{
  internal static class StampSetting
  {
    /// <redirect project="Akelon.StampModule.Shared" type="Akelon.StampModule.Shared.StampSettingFunctions" />
    internal static  void SetVisibleProperties(global::Akelon.StampModule.IStampSetting stampSetting)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)stampSetting).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetVisibleProperties", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Akelon.StampModule.Shared" type="Akelon.StampModule.Shared.StampSettingFunctions" />
    internal static  void SetRequiredProperties(global::Akelon.StampModule.IStampSetting stampSetting)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)stampSetting).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetRequiredProperties", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }

  }
}

// ==================================================================
// StampSettingFilterState.g.cs
// ==================================================================

namespace Akelon.StampModule.Shared.StampSetting
{

  public class StampSettingFilterInfo : global::Sungero.CoreEntities.Shared.DatabookEntry.DatabookEntryFilterInfo,
    global::Akelon.StampModule.IStampSettingFilterInfo
  {
  }

  public class StampSettingFilterState : global::Sungero.CoreEntities.Shared.DatabookEntry.DatabookEntryFilterState,
    global::Akelon.StampModule.IStampSettingFilterState
  {



    public new Akelon.StampModule.IStampSettingFilterInfo Info
    {
      get
      {
        return (Akelon.StampModule.IStampSettingFilterInfo) base.Info;
      }
    }
    protected override global::Sungero.Domain.Shared.IFilterInfo CreateFilterInfo()
    {
      return new Akelon.StampModule.Shared.StampSetting.StampSettingFilterInfo();
    }

  }
}

// ==================================================================
// StampSettingSharedPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Shared
{
  public class StampSettingSharedPublicFunctions : global::Akelon.StampModule.Shared.IStampSettingSharedPublicFunctions
  {
  }
}
