//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Client
{
  /// <summary>
  /// Interaction logic for StampSettingCollectionView.xaml.
  /// </summary>
  public partial class StampSettingCollectionView : global::System.Windows.Controls.UserControl
  {
    public StampSettingCollectionView()
    {
      InitializeComponent();
    }
  }
}