
// ==================================================================
// Module.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Client
{
  public partial class StampModuleModule : global::Sungero.Domain.Shared.ModuleBase
  {
    public override global::System.Guid Id
    {
      get { return global::System.Guid.Parse("afa06e1e-0cb3-4141-a383-ee483bb5bef6"); }
    }

    public override string Name
    {
      get { return "Akelon.StampModule"; }
    }

    public override void RegisterTypes()
    {
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("f934513f-69b5-42cc-8fda-e3774740a380"), new Akelon.StampModule.Shared.StampSettingInfo(typeof(global::Akelon.StampModule.IStampSetting)));
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Akelon.StampModule.Client.IStampSettingClientPublicFunctions, global::Akelon.StampModule.Client.StampSettingClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Akelon.StampModule.Shared.IStampSettingSharedPublicFunctions, global::Akelon.StampModule.Shared.StampSettingSharedPublicFunctions>();


      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Akelon.StampModule.IStampSettingFilterState, global::Akelon.StampModule.Shared.StampSetting.StampSettingFilterState>();



      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Akelon.StampModule.Client.IModuleClientPublicFunctions, global::Akelon.StampModule.Client.ModuleClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Akelon.StampModule.Shared.IModuleSharedPublicFunctions, global::Akelon.StampModule.Shared.ModuleSharedPublicFunctions>();
    }
  }
}
