
// ==================================================================
// StampSettingEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Client
{ 
  public class StampSettingDocumentTypeValueInputEventArgs : global::Sungero.Presentation.ValueInputEventArgs<global::Sungero.Docflow.IDocumentType>
  {
    public StampSettingDocumentTypeValueInputEventArgs(global::Sungero.Docflow.IDocumentType oldValue, global::Sungero.Docflow.IDocumentType newValue, global::Sungero.Domain.Shared.IEntity entity, global::Sungero.Domain.Shared.IPropertyInfo propertyInfo): base(oldValue, newValue, entity, propertyInfo) { }
  }







}

// ==================================================================
// StampSettingHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule
{

  public partial class StampSettingFilteringClientHandler
    : global::Sungero.Domain.EntityFilteringClientHandler
  {
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    protected global::Akelon.StampModule.IStampSettingFilterState Filter { get; private set; }

    private global::Akelon.StampModule.IStampSettingFilterState _filter
    {
      get
      {
        return this.Filter;
      }
    }

    public StampSettingFilteringClientHandler(global::Akelon.StampModule.IStampSettingFilterState filter)
    : base()
    {
      this.Filter = filter;
    }

    protected StampSettingFilteringClientHandler()
    {
    }

    public override void ValidateFilterPanel(global::Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
    }
  }


  public partial class StampSettingClientHandlers : global::Sungero.CoreEntities.DatabookEntryClientHandlers
  {
    private global::Akelon.StampModule.IStampSetting _obj
    {
      get { return (global::Akelon.StampModule.IStampSetting)this.Entity; }
    }

    public virtual void NameValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }


    public virtual void DocumentTypeValueInput(global::Akelon.StampModule.Client.StampSettingDocumentTypeValueInputEventArgs e) { }


    public virtual void StampKindValueInput(global::Sungero.Presentation.EnumerationValueInputEventArgs e) { }


    public virtual void DocumentPositionValueInput(global::Sungero.Presentation.EnumerationValueInputEventArgs e) { }


    public virtual void PagePositionValueInput(global::Sungero.Presentation.EnumerationValueInputEventArgs e) { }





    public virtual global::System.Collections.Generic.IEnumerable<global::Sungero.Core.Enumeration> StampKindFiltering(
      global::System.Collections.Generic.IEnumerable<global::Sungero.Core.Enumeration> query) 
    { 
      return query; 
    }


    public virtual global::System.Collections.Generic.IEnumerable<global::Sungero.Core.Enumeration> DocumentPositionFiltering(
      global::System.Collections.Generic.IEnumerable<global::Sungero.Core.Enumeration> query) 
    { 
      return query; 
    }


    public virtual global::System.Collections.Generic.IEnumerable<global::Sungero.Core.Enumeration> PagePositionFiltering(
      global::System.Collections.Generic.IEnumerable<global::Sungero.Core.Enumeration> query) 
    { 
      return query; 
    }





    public StampSettingClientHandlers(global::Akelon.StampModule.IStampSetting entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// StampSettingClientFunctions.g.cs
// ==================================================================

namespace Akelon.StampModule.Client
{
  public partial class StampSettingFunctions : global::Sungero.CoreEntities.Client.DatabookEntryFunctions
  {
    private global::Akelon.StampModule.IStampSetting _obj
    {
      get { return (global::Akelon.StampModule.IStampSetting)this.Entity; }
    }

    public StampSettingFunctions(global::Akelon.StampModule.IStampSetting entity) : base(entity) { }
  }
}

// ==================================================================
// StampSettingFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Functions
{
  internal static class StampSetting
  {
    /// <redirect project="Akelon.StampModule.Shared" type="Akelon.StampModule.Shared.StampSettingFunctions" />
    internal static  void SetVisibleProperties(global::Akelon.StampModule.IStampSetting stampSetting)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)stampSetting).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetVisibleProperties", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="Akelon.StampModule.Shared" type="Akelon.StampModule.Shared.StampSettingFunctions" />
    internal static  void SetRequiredProperties(global::Akelon.StampModule.IStampSetting stampSetting)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)stampSetting).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetRequiredProperties", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }

  }
}

// ==================================================================
// StampSettingClientPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Client
{
  public class StampSettingClientPublicFunctions : global::Akelon.StampModule.Client.IStampSettingClientPublicFunctions
  {
  }
}

// ==================================================================
// StampSettingActions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Client
{
  public partial class StampSettingActions : global::Sungero.CoreEntities.Client.DatabookEntryActions
  {
    private global::Akelon.StampModule.IStampSetting _obj { get { return (global::Akelon.StampModule.IStampSetting)this.Entity; } }
    public StampSettingActions(global::Akelon.StampModule.IStampSetting entity) : base(entity) { }
  }

  public partial class StampSettingCollectionActions : global::Sungero.CoreEntities.Client.DatabookEntryCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::Akelon.StampModule.IStampSetting> _objs
    {
      get { return global::System.Linq.Enumerable.Cast<global::Akelon.StampModule.IStampSetting>(this.Entities); }
    }
  }

  public partial class StampSettingCollectionBulkActions : global::Sungero.CoreEntities.Client.DatabookEntryCollectionBulkActions
  {
    private global::System.Collections.Generic.IEnumerable<global::System.Int32> _objIds
    {
      get { return this.EntityIds; }
    }
  }


  public partial class StampSettingAnyChildEntityActions : global::Sungero.CoreEntities.Client.DatabookEntryAnyChildEntityActions
  {
  }

  public partial class StampSettingAnyChildEntityCollectionActions : global::Sungero.CoreEntities.Client.DatabookEntryAnyChildEntityCollectionActions
  {
  }



}
