
// ==================================================================
// ModuleFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Functions
{
  internal static partial class Module
  {
    internal static class Remote
    {
      /// <redirect project="Akelon.StampModule.Server" type="Akelon.StampModule.Server.ModuleFunctions" />
      internal static global::System.String CreateDocumentStamp(global::Sungero.Docflow.IOfficialDocument document)
      {
        return global::Sungero.Domain.Shared.RemoteFunctionExecutor.ExecuteWithResult<global::System.String>(
          global::System.Guid.Parse("afa06e1e-0cb3-4141-a383-ee483bb5bef6"),
          "CreateDocumentStamp(global::Sungero.Docflow.IOfficialDocument)", document);
      }

    }
    private static object GetFunctionsContainer()
    {
      return new global::Akelon.StampModule.Shared.ModuleFunctions();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType, global::Sungero.Metadata.ModuleMetadata finalModuleMetadatda)
    {
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.FunctionNamespace, "Module", assemblyName));
      var methodInfo = moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static);
      return global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, null, null);
    }
  }
}

// ==================================================================
// ModuleHyperlinks.g.cs
// ==================================================================

namespace Akelon.StampModule
{
  public static class StampModuleClientFunctionHyperlinksExtensions
  {
  }
}

// ==================================================================
// ModuleResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Shared
{
  public class ModuleResources : global::Akelon.StampModule.IModuleResources
  {
    public virtual global::CommonLibrary.LocalizedString MsgNotSettingByStampKind
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("afa06e1e-0cb3-4141-a383-ee483bb5bef6")) , "MsgNotSettingByStampKind", false);
      }
    }

    public virtual global::CommonLibrary.LocalizedString MsgNotSettingByStampKindFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("afa06e1e-0cb3-4141-a383-ee483bb5bef6")), "MsgNotSettingByStampKind", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString MsgStampInstalled
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("afa06e1e-0cb3-4141-a383-ee483bb5bef6")) , "MsgStampInstalled", false);
      }
    }

    public virtual global::CommonLibrary.LocalizedString MsgStampInstalledFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("afa06e1e-0cb3-4141-a383-ee483bb5bef6")), "MsgStampInstalled", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString MsgNotFoundStampSetting
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("afa06e1e-0cb3-4141-a383-ee483bb5bef6")) , "MsgNotFoundStampSetting", false);
      }
    }

    public virtual global::CommonLibrary.LocalizedString MsgNotFoundStampSettingFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("afa06e1e-0cb3-4141-a383-ee483bb5bef6")), "MsgNotFoundStampSetting", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString DialogTopicSetStamp
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("afa06e1e-0cb3-4141-a383-ee483bb5bef6")) , "DialogTopicSetStamp", false);
      }
    }

    public virtual global::CommonLibrary.LocalizedString DialogTopicSetStampFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("afa06e1e-0cb3-4141-a383-ee483bb5bef6")), "DialogTopicSetStamp", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString DialogFieldDocument
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("afa06e1e-0cb3-4141-a383-ee483bb5bef6")) , "DialogFieldDocument", false);
      }
    }

    public virtual global::CommonLibrary.LocalizedString DialogFieldDocumentFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("afa06e1e-0cb3-4141-a383-ee483bb5bef6")), "DialogFieldDocument", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString DialogMsgNotVersions
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("afa06e1e-0cb3-4141-a383-ee483bb5bef6")) , "DialogMsgNotVersions", false);
      }
    }

    public virtual global::CommonLibrary.LocalizedString DialogMsgNotVersionsFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(System.Guid.Parse("afa06e1e-0cb3-4141-a383-ee483bb5bef6")), "DialogMsgNotVersions", false, args);
    }

  }
}

// ==================================================================
// ModuleFoldersFilterStates.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Shared
{
}

// ==================================================================
// ModuleSharedPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Shared
{
  public partial class ModuleSharedPublicFunctions : global::Akelon.StampModule.Shared.IModuleSharedPublicFunctions
  {
  }
}

// ==================================================================
// ModuleWidgetParameters.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.StampModule.Shared
{  
}
