
// ==================================================================
// Module.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akelon.DocumentStamp.Client
{
  public partial class DocumentStampModule : global::Sungero.Domain.Shared.ModuleBase
  {
    public override global::System.Guid Id
    {
      get { return global::System.Guid.Parse("2a7a63e7-8570-4623-97c1-bac71f31050f"); }
    }

    public override string Name
    {
      get { return "Akelon.DocumentStamp"; }
    }

    public override void RegisterTypes()
    {




      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Akelon.DocumentStamp.Client.IModuleClientPublicFunctions, global::Akelon.DocumentStamp.Client.ModuleClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Akelon.DocumentStamp.Shared.IModuleSharedPublicFunctions, global::Akelon.DocumentStamp.Shared.ModuleSharedPublicFunctions>();
    }
  }
}
